#!/usr/bin/env python3
"""
Build vocab.js from data/*.txt for offline play.

Reads top-level *.txt files in the data directory (same rules as db.seed_words_from_files).
Outputs a JavaScript file defining VOCAB (theme -> words) and THEMES (id, name, display, word_count).
"""
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATA_DIR = ROOT / "data"
DEFAULT_OUTPUT = ROOT / "vocab.js"


def theme_display_name(theme_name: str) -> str:
    """Mirror db.theme_display_name: KET_ANIMALS -> Animals."""
    if not theme_name or not theme_name.strip():
        return "Vocabulary"
    parts = theme_name.strip().split("_")
    return parts[-1].title() if parts else theme_name


def collect_word_files(source_dirs: list[Path]) -> list[Path]:
    """Top-level *.txt only in each directory."""
    files = []
    for directory in source_dirs:
        if not directory.exists() or not directory.is_dir():
            continue
        files.extend(sorted(directory.glob("*.txt")))
    return files


def build_vocab_and_themes(data_dir: Path) -> tuple[dict[str, list[str]], list[dict]]:
    vocab = {}
    themes = []
    for file_path in collect_word_files([data_dir]):
        theme_name = file_path.stem.upper()
        words = []
        for line in file_path.read_text(encoding="utf-8").splitlines():
            word = line.strip().lower()
            if word:
                words.append(word)
        if theme_name:
            vocab[theme_name] = words
            themes.append({
                "id": theme_name,
                "name": theme_name,
                "display": theme_display_name(theme_name),
                "word_count": len(words),
            })
    return vocab, themes


def emit_js(vocab: dict, themes: list[dict], out_path: Path) -> None:
    """Write vocab.js with VOCAB and THEMES."""
    vocab_json = json.dumps(vocab, ensure_ascii=False)
    themes_json = json.dumps(themes, ensure_ascii=False)
    content = f"""// Generated by scripts/build_vocab_js.py — do not edit by hand.
const VOCAB = {vocab_json};
const THEMES = {themes_json};
"""
    out_path.write_text(content, encoding="utf-8")


def main() -> int:
    data_dir = ROOT / "data" if len(sys.argv) < 2 else Path(sys.argv[1]).resolve()
    out_path = DEFAULT_OUTPUT if len(sys.argv) < 3 else Path(sys.argv[2]).resolve()

    if not data_dir.is_dir():
        print(f"Error: data directory not found: {data_dir}", file=sys.stderr)
        return 1

    vocab, themes = build_vocab_and_themes(data_dir)
    if not vocab:
        print("Warning: no vocabulary files found.", file=sys.stderr)

    emit_js(vocab, themes, out_path)
    print(f"Wrote {out_path} ({len(themes)} themes, {sum(len(w) for w in vocab.values())} words).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
